# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'go_to_test_page_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 550)
        self.go_to_test_btn = QtWidgets.QPushButton(Form)
        self.go_to_test_btn.setGeometry(QtCore.QRect(250, 450, 150, 41))
        font = QtGui.QFont()
        font.setFamily("Object Sans Heavy")
        font.setPointSize(10)
        self.go_to_test_btn.setFont(font)
        self.go_to_test_btn.setStyleSheet("color:#FFFFFF;background:#001D3D;border-radius:15px;font-family:\"Object Sans Heavy\";")
        self.go_to_test_btn.setObjectName("go_to_test_btn")
        self.info_label = QtWidgets.QLabel(Form)
        self.info_label.setGeometry(QtCore.QRect(144, 0, 371, 451))
        font = QtGui.QFont()
        font.setFamily("Object Sans Heavy")
        font.setPointSize(12)
        self.info_label.setFont(font)
        self.info_label.setStyleSheet("color: #003566;font-family:\"Object Sans Heavy\";background:transparent;")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.back_btn = QtWidgets.QPushButton(Form)
        self.back_btn.setGeometry(QtCore.QRect(20, 520, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet(" background: transparent;color:#001D3D;border:2px solid #003566;border-radius:5;text-decoration:none\n"
"\n"
"")
        self.back_btn.setObjectName("back_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.go_to_test_btn.setText(_translate("Form", "ПРОЙТИ\n"
"ТЕСТ"))
        self.info_label.setText(_translate("Form", "В тесте вам будет предложено указать случайный признак рандомного слова. Количество вопростов в тесте не ограничено, Вы сможете завершить тест в любой момент\n"
"\n"
"Для того чтобы завершить тест или перейти к следующему вопросу, нужно ответить на предложенный вопрос\n"
"\n"
"После завершения теста вы сможете узнать свои результаты, скачав файл. Данная функция доступна только авторизованным пользователям"))
        self.back_btn.setText(_translate("Form", "← Назад"))
