# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_page_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 550)
        Form.setMinimumSize(QtCore.QSize(650, 550))
        self.word_label = QtWidgets.QLabel(Form)
        self.word_label.setGeometry(QtCore.QRect(0, 40, 650, 41))
        font = QtGui.QFont()
        font.setFamily("Object Sans Heavy")
        font.setPointSize(16)
        self.word_label.setFont(font)
        self.word_label.setStyleSheet("font-family:\"Object Sans Heavy\";")
        self.word_label.setAlignment(QtCore.Qt.AlignCenter)
        self.word_label.setObjectName("word_label")
        self.end_test_btn = QtWidgets.QPushButton(Form)
        self.end_test_btn.setGeometry(QtCore.QRect(20, 480, 150, 41))
        font = QtGui.QFont()
        font.setFamily("Object Sans Heavy")
        font.setPointSize(10)
        self.end_test_btn.setFont(font)
        self.end_test_btn.setStyleSheet("color:#FFFFFF;background:#001D3D;border-radius:15px;font-family:\"Object Sans Heavy\";")
        self.end_test_btn.setObjectName("end_test_btn")
        self.next_btn = QtWidgets.QPushButton(Form)
        self.next_btn.setGeometry(QtCore.QRect(480, 480, 150, 41))
        font = QtGui.QFont()
        font.setFamily("Object Sans Heavy")
        font.setPointSize(10)
        self.next_btn.setFont(font)
        self.next_btn.setStyleSheet("color:#FFFFFF;background:#001D3D;border-radius:15px;font-family:\"Object Sans Heavy\";")
        self.next_btn.setObjectName("next_btn")
        self.answer_variants = QtWidgets.QComboBox(Form)
        self.answer_variants.setGeometry(QtCore.QRect(200, 230, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Object Sans Heavy")
        font.setPointSize(12)
        self.answer_variants.setFont(font)
        self.answer_variants.setStyleSheet("color:#FFFFFF;background:#001D3D;border-radius:15px;font-family:\"Object Sans Heavy\"\n"
"\n"
"")
        self.answer_variants.setObjectName("answer_variants")
        self.sign_label = QtWidgets.QLabel(Form)
        self.sign_label.setGeometry(QtCore.QRect(0, 140, 650, 31))
        font = QtGui.QFont()
        font.setFamily("Object Sans Heavy")
        font.setPointSize(15)
        self.sign_label.setFont(font)
        self.sign_label.setStyleSheet("font-family:\"Object Sans Heavy\"")
        self.sign_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sign_label.setObjectName("sign_label")
        self.answer_label = QtWidgets.QLabel(Form)
        self.answer_label.setGeometry(QtCore.QRect(210, 420, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Object Sans Heavy")
        font.setPointSize(10)
        self.answer_label.setFont(font)
        self.answer_label.setStyleSheet("font-family:\"Object Sans Heavy\";")
        self.answer_label.setText("")
        self.answer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.answer_label.setObjectName("answer_label")
        self.answer_btn = QtWidgets.QPushButton(Form)
        self.answer_btn.setGeometry(QtCore.QRect(250, 480, 150, 41))
        font = QtGui.QFont()
        font.setFamily("Object Sans Heavy")
        font.setPointSize(10)
        self.answer_btn.setFont(font)
        self.answer_btn.setStyleSheet("color:#FFFFFF;background:#001D3D;border-radius:15px;font-family:\"Object Sans Heavy\";")
        self.answer_btn.setObjectName("answer_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.word_label.setText(_translate("Form", "Слово для разбора: машина"))
        self.end_test_btn.setText(_translate("Form", "ЗАВЕРШИТЬ ТЕСТ"))
        self.next_btn.setText(_translate("Form", "ДАЛЕЕ"))
        self.sign_label.setText(_translate("Form", "Выберите род"))
        self.answer_btn.setText(_translate("Form", "ОТВЕТИТЬ"))
